### ISSUE TITLE
chat and command

### ISSUE THREAD

**Issue by ghost** [AuthMe/AuthMeBungee#12]
any command or message in chat not work
![2017-12-04_00 14 46](https://user-images.githubusercontent.com/5884000/33531050-6455c680-d888-11e7-86c3-7666523606f9.png)

config
```

# List of servers which required to be authenticated
authServers:
- 'hub'
commands:
    # Allows or not commands to be performed if user is not logged in
    requireAuth: true
    # List of commands allowed to be perform without being authenticated
    whitelist: 
    - '/login'
    - '/register'
    - '/l'
    - '/reg'
    - '/email'
    - '/captcha'
# Allows or not user to talk in chat if he is not logged in
chatRequiresAuth: true
serverSwitch:
    # Kick all players who switch servers without being authenticated (eg. plugin teleport)
    requiresAuth: true
    kickMessage: 'Authentication required.'
# Enable auto-login between servers
autoLogin: true
```

only i can use a /login or /register

yes, I'm already logged in

on any other servers in my network i have the same problem

travertine
`https://ci.lucko.me/job/Travertine/`

plugins
```
SkinsRestorer-v13.1.3.jar
ServerListPlus-3.4.7-Universal.jar
LuckPerms-Bungee-4.0.10.jar
BungeeTabListPlus-2.8.3-SNAPSHOT.jar
BungeeChat-2.1.6.855.jar
bungeeban-2.6.7.jar
BungeeAliases-1.1.4.jar
authmebungee-2.0.1-SNAPSHOT.jar
```
