### ISSUE TITLE
Configuration issues

### ISSUE THREAD

**Issue by abxup** [AuthMe/AuthMeBungee#148]
I don't know if it's my fault or the plugin's fault. I originally pointed to install Authme for a sub-server, and then the player needs to enter the server with Authme installed to log in after entering the game. After the login is completed, you can play the game, but! This is my configuration file:
```
authServers:
- lobby
# 将每个服务器视为身份验证服务器
allServersAreAuthServers: false
commands:
    # 允许或禁止在用户未登录时执行命令
    requireAuth: true
    # 允许在未经身份验证的情况下执行的命令列表
    whitelist:
    - /login
    - /register
    - /l
    - /reg
    - /email
    - /captcha
# 允许或禁止用户在未登录时在聊天中发言
chatRequiresAuth: true
serverSwitch:
    # 强制要求进行身份验证后才能切换服务器（例如插件传送）
    requiresAuth: true
    kickMessage: 需要身份验证。
# 启用服务器间的自动登录
autoLogin: false
# 如果启用，未登录的用户将被发送到unloggedUserServer服务器！
sendOnLogout: true
# 如果sendOnLogout启用，未登录的用户将被发送到此服务器！
unloggedUserServer: 'lobby'
```
However, when the player exits, they will still return to the server they left out from
