### ISSUE TITLE
Cannot block bungee command

### ISSUE THREAD

**Issue by cocomine** [AuthMe/AuthMeBungee#18]
Can still use the bungee command without logging in

```
# List of servers which required to be authenticated
authServers: 
- 'lobby'
- 'WizardOfDream'
- 'MiniGame'
commands:
    # Allows or not commands to be performed if user is not logged in
    requireAuth: true
    # List of commands allowed to be perform without being authenticated
    whitelist: 
    - '/login'
    - '/register'
    - '/l'
    - '/reg'
    - '/email'
    - '/captcha'
# Allows or not user to talk in chat if he is not logged in
chatRequiresAuth: true
serverSwitch:
    # Kick all players who switch servers without being authenticated (eg. plugin teleport)
    requiresAuth: true
    kickMessage: 'Login again Plz'
# Enable auto-login between servers
autoLogin: true
# If enabled, unlogged users will be sent to the unloggedUserServer server!
sendOnLogout: false
# If sendOnLogout is enabled, unlogged users will be sent to this server!
unloggedUserServer: '' 
```
  
```
 servers:
  lobby:
    motd: '           &e▁&d▂&c▃&b▅&a▆&a&lCoco&b&lPixel&d&l&oMC&r&9 Server&a▆&b▅&c▃&d▂&e▁           &c&lPrivate
      server   &6&k &a&o   Lobby to active server'
    address: 127.0.0.1:43265
    restricted: false
  WizardOfDream:
    motd: Wizard Of Dream
    address: 127.0.0.1:23498
    restricted: false
  MiniGame:
    motd: MiniGame
    address: 127.0.0.1:44586
    restricted: false
```
