### ISSUE TITLE
Command cannot be used after login

### ISSUE THREAD

**Issue by 4o4E** [AuthMe/AuthMeBungee#91]
**What behaviour is observed:**
Command cannot be used after login. After entering the command, there is no response, and there is no message in the console. Other functions are normal.

**What behaviour is expected:**
Command can be use

**Steps/models to reproduce:**
1.login
2.use command

Plugin list:
AuthMe

**Environment description**
server:
Paper version git-Paper-"4e2f0be" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
Previous version: git-Paper-"1830de5" (MC: 1.17)

**bungeecord:**
Command cannot be used on both bungeecord(1590) and waterfall(1.17-438)

**AuthMe build number:**
AuthMeReloaded v5.6.0-SNAPSHOT (build: 2480)

**Error Log:**
There are no error logs

**Configuration:**
server's config is default config
bungee's config https://pastebin.com/9FkgHxcF

**Comment by Link0Darck** [comment]
I have the same problem as this person his brand authentication is required and I have activated this option (sessions) and the problem is that AuthMeBungee does not often take into account the sessions

thank you in advance for correcting the problem
`    sessions:
        # Do you want to enable the session feature?
        # If enabled, when a player authenticates successfully,
        # his IP and his nickname is saved.
        # The next time the player joins the server, if his IP
        # is the same as last time and the timeout hasn't
        # expired, he will not need to authenticate.
        enabled: true
        # After how many minutes should a session expire?
        # A player's session ends after the timeout or if his IP has changed
        timeout: 10`

**Comment by 4o4E** [comment]
Thank you for your reply, but I tried to switch the sessions option and found it didn't work

**Comment by Link0Darck** [comment]
Hello, have you activated this option?
if so, deactivate it and test to see if your problem is solved
`serverSwitch:
    # Kick all players who switch servers without being authenticated (eg. plugin teleport)
    requiresAuth: false
    kickMessage: Authentification requise.
`

**Comment by 4o4E** [comment]
I tried to switch, but it didn't work

**Comment by Explosion-Of-Generation** [comment]
have you hook authme with authmebungee?
I also experienced the same thing a few minutes ago

make sure 'bungeecord' which is in 'spigot.yml' file on your lobby server is active, and ip-forward which is in 'config.yml' on your bungeecord server is also active

after you make sure it's active change the command on the bungeecord server -> AuthMeBungee -> config.yml
```
allServersAreAuthServers: true
requireAuth: false
chatRequiresAuth: false
requiresAuth: false
autoLogin: true
sendOnLogout: false
```

don't forget to activate your authme hook which is on the lobby server
```
Hooks:
    # Do we need to hook with multiverse for spawn checking?
    multiverse: true
    # Do we need to hook with BungeeCord?
    bungeecord: true
    # Send player to this BungeeCord server after register/login
    sendPlayerTo: ''
    # Do we need to disable Essentials SocialSpy on join?
    disableSocialSpy: false
    # Do we need to force /motd Essentials command on join?
    useEssentialsMotd: false
```

Hope you can help
